# Generated by Django 2.2.4 on 2019-09-02 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 16, 32, 16, 777397), verbose_name='date published'),
        ),
    ]
