# Generated by Django 2.2.4 on 2019-09-02 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190902_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 16, 46, 11, 963776), verbose_name='date published'),
        ),
    ]
